[build]
  base = "."
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_ENABLED = "true"
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_BASE_URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
